apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pet-deploy
  name: kezang-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kezang-deploy
  template:
    metadata:
      labels:
        app: kezang-deploy
    spec:
      containers:
      - image: kezangyuden/kezangy:latest
        name: pet
